// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logx

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func Wire() (*LogX, error) {
	logX := Provide()
	return logX, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	Provide,
)
