// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apikey

import (
	"github.com/google/wire"
	"go-fiber-api/internal/core/config"
	"go-fiber-api/internal/core/storage/db"
)

// Injectors from wire.go:

func Wire(cfg *config.Configuration, client db.Client) (Handler, error) {
	repo := ProvideRepository(client)
	service := ProvideService(cfg, repo)
	handler := ProvideHandler(service)
	return handler, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	ProvideRepository,

	ProvideService,

	ProvideHandler,
)
