// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cache

import (
	"github.com/google/wire"
	"go-fiber-api/internal/wrapper/redis"
)

// Injectors from wire.go:

func Wire(client redis.Client) CacheMiddleware {
	cacheMiddleware := New(client)
	return cacheMiddleware
}

// wire.go:

var ProviderSet = wire.NewSet(
	New,
)
