// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"github.com/google/wire"
	"go-fiber-api/internal/wrapper/logx"
)

// Injectors from wire.go:

func Wire(logx2 *logx.LogX) (*Configuration, error) {
	configuration := Provide(logx2)
	return configuration, nil
}

// wire.go:

var ProviderSet = wire.NewSet(
	Provide,
)
